apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-inventory
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/env: prod
    stakater.com/kind: prod
spec:
  destination:
    namespace: veeru-prod
  source:
    path: 02-veeru/01-stakater-nordmart-inventory/prod
