apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-inventory
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/env: dev
    stakater.com/kind: dev
spec:
  destination:
    namespace: veeru-dev
  source:
    path: 02-veeru/01-stakater-nordmart-inventory/dev
