
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-dev-review-ui
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/tenant: gabbar
    stakater.com/env: dev
    stakater.com/kind: dev  
spec:
  destination:
    namespace: gabbar-dev
    server: 'https://kubernetes.default.svc'
  project: gabbar
  source:
    path: 01-gabbar/apps/02-stakater-nordmart-review-ui/03-dev
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

