apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-stakater-nordmart-review
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/env: dev
    stakater.com/kind: dev
spec:
  destination:
    namespace: gabbar-dev
  source:
    path: 01-gabbar/01-stakater-nordmart-review/dev


