apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-review-ui
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/env: dev
    stakater.com/kind: dev
spec:
  destination:
    namespace: gabbar-dev
  source:
    path: 01-gabbar/02-stakater-nordmart-review-ui/dev

