apiVersion: tenantoperator.stakater.com/v1beta1
kind: Tenant
metadata:
  name: gabbar
spec:
  quota: medium
  owners:
    users:
      - nebojsa
      - bilal.bokharee@stakater.com
      - hanzala@stakater.com
      - shahid@stakater.com
  argocd:
    sourceRepos:
      - 'https://github.com/stakater/gitops-config-template'
  templateInstances:
  - spec:
      template: tenant-vault-access
      sync: true
  namespaces:
  - build
  - preview
  - dev
  - stage
  - prod
