
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-stage-stakater-nordmart-review
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/tenant: gabbar
    stakater.com/env: stage
    stakater.com/kind: stage         
spec:
  destination:
    namespace: gabbar-stage
    server: 'https://kubernetes.default.svc'
  source:
    path: 01-gabbar/apps/01-stakater-nordmart-review/02-stage
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: HEAD
  project: gabbar 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

