apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-stakater-nordmart-review
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/env: stage
    stakater.com/kind: stage
spec:
  destination:
    namespace: gabbar-stage
  source:
    path: 01-gabbar/01-stakater-nordmart-review/stage


