apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-review-ui
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/env: stage
    stakater.com/kind: stage
spec:
  destination:
    namespace: gabbar-stage
  source:
    path: 01-gabbar/02-stakater-nordmart-review-ui/stage

