apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Tenant
metadata:
  name: veeru
spec:
  users:
   owner:
    - hanzala@stakater.com
    # Test user for Stakater Cloud IAM
    - sro-privileged
  quota: medium
