apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-stage-inventory
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/tenant: veeru
    stakater.com/env: stage
    stakater.com/kind: stage     
spec:
  destination:
    namespace: veeru-stage
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-veeru/apps/01-stakater-nordmart-inventory/02-stage
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
  project: veeru
  syncPolicy:
    automated:
      prune: true