apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-stakater-nordmart-review
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/env: prod
    stakater.com/kind: prod
spec:
  destination:
    namespace: gabbar-prod
  source:
    path: 01-gabbar/01-stakater-nordmart-review/prod


