apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-build
  namespace: openshift-stakater-argocd
spec:
  destination:
    namespace: gabbar-build
    server: 'https://kubernetes.default.svc'
  source:
    path: 01-gabbar/configs/00-build/
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
    directory:
       recurse: true
  project: gabbar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
