apiVersion: tenantoperator.stakater.com/v1beta1
kind: Quota
metadata:
  name: small
  annotations:
    quota.tenantoperator.stakater.com/is-default: "false"
spec:
  resourcequota:
    hard:
      requests.cpu: "2"
      requests.memory: 4Gi
  limitrange:
    limits:
      - defaultRequest:
          cpu: 100m
          memory: 100Mi
        type: Container