apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-review-ui
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/tenant: gabbar
    stakater.com/env: base
    stakater.com/kind: base
spec:
  destination:
    namespace: gabbar-base
    server: 'https://kubernetes.default.svc'
  project: gabbar
  source:
    path: 01-gabbar/02-stakater-nordmart-review-ui/base
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

